endpoints:
  - name: qwen38-prefill
    address: "172.18.0.4"
    port: "8100"
    labels:
      role: prefill
  - name: qwen38-decode-sidecar
    address: "172.18.0.2"
    port: "8200"
    labels:
      role: decode
