plugins:
  - name: file-disc
    type: file-discovery
    parameters:
      path: /workspace/llmd-config/endpoints-disagg.yaml
      watchFile: true
  - name: prefill-pods
    type: label-selector-filter
    parameters:
      matchExpressions:
        - key: role
          operator: In
          values: [prefill]
  - name: decode-pods
    type: label-selector-filter
    parameters:
      matchExpressions:
        - key: role
          operator: In
          values: [decode]
  - name: random-picker
    type: random-picker
  - name: always-pd
    type: always-disagg-pd-decider
  - name: disagg-handler
    type: disagg-profile-handler
    parameters:
      profiles:
        prefill: prefill
        decode: decode
      deciders:
        prefill: always-pd

schedulingProfiles:
  - name: prefill
    plugins:
      - pluginRef: prefill-pods
      - pluginRef: random-picker
  - name: decode
    plugins:
      - pluginRef: decode-pods
      - pluginRef: random-picker

dataLayer:
  discovery:
    pluginRef: file-disc
