apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: token-labs
resources:
- deployment.yaml
- model-list-policy.yaml
configMapGenerator:
- name: model-aggregator-code
  files:
  - aggregator.py
