inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/model: qwen3-30b-control-llm-d
inferenceExtension:
  replicas: 1
  image:
    registry: ghcr.io
    repository: llm-d/llm-d-router-endpoint-picker
    tag: v0.10.0
    pullPolicy: IfNotPresent
  extProcPort: 9002
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 1Gi
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: ["amd64"]
provider:
  name: none
